# Generated by Django 4.2.13 on 2024-07-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_last_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
